
"use strict";
const D=window.PROJECT_DATA;
const colors=['#2458e6','#b45a15','#7742cc','#147a60','#bd3463','#3a7588'];
const fmt=n=>Number(n).toLocaleString('en-GB',{maximumFractionDigits:0});
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=id=>document.getElementById(id);
function stats(items){el('stats').innerHTML=items.map(([label,value,note])=>`<div class="stat"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div><div class="note">${esc(note)}</div></div>`).join('')}
function bars(target,items,formatter=money){const max=Math.max(...items.map(x=>x.value),1);el(target).innerHTML=items.length?items.map((x,i)=>`<div><div class="bar-label"><span>${esc(x.label)}</span><strong>${esc(formatter(x.value))}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,x.value/max*100)}%;background:${x.color||colors[0]}"></div></div></div>`).join(''):'<p class="subtle">No sales for this selection.</p>'}
function lineChart(target,rows,series,formatLabel=r=>r.date){const w=760,h=290,p={l:90,r:40,t:20,b:48},max=Math.max(...rows.flatMap(r=>series.map(s=>r[s.key])),1)*1.1;let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(series.map(s=>s.label).join(' and '))} by date">`;
for(let i=0;i<=4;i++){let y=p.t+(h-p.t-p.b)*i/4;svg+=`<line x1="${p.l}" x2="${w-p.r}" y1="${y}" y2="${y}"/><text x="${p.l-10}" y="${y+5}" text-anchor="end">${fmt(max*(1-i/4))}</text>`}
series.forEach(s=>{let pts=rows.map((r,i)=>`${p.l+i/Math.max(1,rows.length-1)*(w-p.l-p.r)},${p.t+(1-r[s.key]/max)*(h-p.t-p.b)}`).join(' ');svg+=`<polyline points="${pts}" fill="none" stroke="${s.color}" stroke-width="2.4"/>`});
const count=Math.min(5,rows.length);for(let j=0;j<count;j++){let i=Math.round(j*(rows.length-1)/Math.max(1,count-1));svg+=`<text x="${p.l+i/Math.max(1,rows.length-1)*(w-p.l-p.r)}" y="${h-13}" text-anchor="middle">${esc(formatLabel(rows[i]))}</text>`}el(target).innerHTML=svg+'</svg>'}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

function updateRetail(){const country=el('country').value,month=el('month').value;const s=D.slices[country][month]||{sales:0,orders:0,customers:0,aov:0,products:[]};stats([['Positive sales',money(s.sales),'GBP · refunds excluded'],['Orders',fmt(s.orders),'Distinct positive-sale invoices'],['Known customers',fmt(s.customers),'Unique IDs in this selection'],['Average order value',money(s.aov),'Positive sales / orders']]);bars('products',s.products.map(p=>({label:p.name,value:p.sales})));const trend=D.trends[country];lineChart('trend',trend,[{key:'sales',label:'Positive sales in GBP',color:colors[0]}],r=>r.month);el('trend-caption').textContent=country+' · full available timeline · GBP';el('product-caption').textContent=country+' · '+month;el('monthly-table').innerHTML=table(['Month','Positive sales (GBP)'],trend.map(r=>[r.month,money(r.sales)]));}
el('country').innerHTML=['All countries',...D.countries].map(c=>`<option>${esc(c)}</option>`).join('');el('month').innerHTML=['All months',...D.months].map(m=>`<option>${esc(m)}</option>`).join('');el('country').addEventListener('change',updateRetail);el('month').addEventListener('change',updateRetail);el('audit').innerHTML=table(['Cleaning stage','Rows'],[['Original records',fmt(D.audit.raw_rows)],['Exact duplicates removed',fmt(D.audit.duplicate_rows)],['Cancellation / negative records removed',fmt(D.audit.cancellation_or_negative_rows)],['Nonpositive / invalid rows removed',fmt(D.audit.nonpositive_or_invalid_rows)],['Positive sales records retained',fmt(D.audit.clean_rows)],['Retained rows missing customer ID',fmt(D.audit.missing_customer_rows_retained)]]);updateRetail();
